<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>net8.0;net9.0;net10.0</TargetFrameworks>
    <CsWinRTWindowsMetadata>10.0.26100.0</CsWinRTWindowsMetadata>
    <CsWinRTIncludes>MicaWPFRuntimeComponent</CsWinRTIncludes>
    <CsWinRTGeneratedFilesDir>$(OutDir)</CsWinRTGeneratedFilesDir>
    <Platform>AnyCPU</Platform>
    <ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>None</ResolveAssemblyWarnOrErrorOnTargetArchitectureMismatch>
    <PublishRepositoryUrl>true</PublishRepositoryUrl>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <EmbedUntrackedSources>true</EmbedUntrackedSources>
    <Deterministic>true</Deterministic>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>portable</DebugType>
    <AssemblyVersion>1.2.0</AssemblyVersion>
    <FileVersion>1.2.0</FileVersion>
    <Version>1.2.0</Version>
    <PackageReadmeFile>README.md</PackageReadmeFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference
      Include="Microsoft.Windows.CsWinRT"
      Version="2.3.1"
      PrivateAssets="all" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference
      Include="..\MicaWPFRuntimeComponent\MicaWPFRuntimeComponent.vcxproj" />
  </ItemGroup>

  <PropertyGroup>
    <GeneratedNugetDir>$(MSBuildProjectDirectory)\nuget\</GeneratedNugetDir>
    <NuspecFile>$(GeneratedNugetDir)MicaWPF.Projection.nuspec</NuspecFile>
    <PackageOutputPath>$(GeneratedNugetDir)</PackageOutputPath>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
  </PropertyGroup>

</Project>
